spring:
  profiles:
    active: dev

---
spring:
  profiles: prod
  application:
    name: microconfig9004 
  cloud:
     config:
       uri: http://localhost:3301
       label: master
       profile: prod

---
spring:
  profiles: default
  application:
    name: microconfig9004 
server:
  port: 9004 

---
spring:
  profiles: dev
  application:
    name: config-single-client
  cloud:
     config:
       uri: http://localhost:3301
       label: master
       profile: dev