server:
  port: 8001
spring:
  profiles: prod 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=gbk&serverTimezone=UTC
    username: root
    password: luomengxuanhaoren
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: Myprvoider-1   #这个名字是微服务名称 ，consumer调用者名称，从而可以达到一个访问consumer能调用多个provider的功能
eureka:
  client:
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 30
    service-url: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://mycode.cn:7001/eureka/,http://mycode.cn:7002/eureka/
#      defaultZone: http://mycode.cn:7001/eureka/
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: myprvoider-01  #此微服务的进程名
info:
  app.name:  myprvoider-1
  version: 1.2
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream